server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/utilisateurs/**
        - id: subscription-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/abonnements/**
        - id: ticket-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tickets/**
        - id: timetable-service
          uri: http://localhost:8181
          predicates:
            - Path=/bus/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
